---

########################################################################
- name: Setup Docker Swarm
########################################################################
  block:

  - name: initialize swarm cluster
    shell: >
      docker swarm init --advertise-addr={{ ipaddress }}:2377
    when: node == "master"
    ignore_errors: true

  - name: add swarm worker
    shell: >
      docker swarm join --token {{ swarm_worker_token }} {{ swarm_manager_ip }}:2377
    when: node == "worker"

  tags: docker_swarm